name: CD-master

on:
  push:
    branches:
    - master

jobs:

  CI: 
    name: CI
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: |
        npm i
        npm run build --if-present
        npm test --if-present
      env:
        CI: true
  CD:
    name: CD
    runs-on: ubuntu-latest
    needs: CI

    steps: 
    - uses: appleboy/ssh-action@master
      with: 
        host: $${{ secrets.HOST }}
        username: $${{ secrets.USERNAME }}
        key: $${{ secrets.KEY }}
        passphrase: $${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/master/${ name }
          git pull
          source ~/.nvm/nvm.sh
          nvm use 14.0.0
          npm i
          npm run build --if-present
          pm2 reload ecosystem.config.js
