name: CI

on: pull_request

jobs:

  CI: 
    name: CI
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14.x'
    - run: |
        npm i
        npm run build --if-present
        npm test --if-present
      env:
        CI: true
        